### ISSUE TITLE
Game speed and player rotation bug

### ISSUE THREAD

**Issue by mikxingu** [luturol/RoadBuilder3D#1]
Whats up bro! I played your game on itch.io, the idea is simple but I enjoyed playing the game, but it seems to be very slow paced. I believe you could increase the speed the plataform builds and falls, because it is kind of annoying to wait for the plataform to build up, and then wait for it to sloooooowly fall on the ground.
Another thing to point out is that sometimes, I don't know why, the player character starts to rotate on its on an then falls from the plataform without any input. I suspect the plataform colliders or (probably) the rigidbody is adding some kind of force on the player.
That's it. Let me know what you think about all I said, and keep it up. It's awesome to play games made by beginner gamedevs, specially people from Brazil. 🇧🇷 .
Lemme know if you need help, I'd love to contribute and learn with you. Cheers and sucess on your projects.

**Comment by luturol** [comment]
Fixed in this [commit](https://github.com/luturol/RoadBuilder3D/commit/df62e5124628caff805c00545a4db8712e081d3f).
